# Generated by Django 3.0.3 on 2020-08-05 21:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antennas", "0002_auto_20200805_2149"),
    ]

    operations = [
        migrations.AddField(
            model_name="antenna",
            name="antpos_enu",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=[0, 0, 0], size=3
            ),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="adc_hist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.FloatField(), size=None
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="eq_coeffs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="fem_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="fem_imu",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=2
            ),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="fem_lna_power",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="fem_temp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="fft_overflow",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="snap_channel_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="antennastatus",
            name="snap_hostname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
