# Generated by Django 3.0.3 on 2020-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antennas", "0005_auto_20200805_2158"),
    ]

    operations = [
        migrations.AddField(
            model_name="antennastatus",
            name="adc_mean",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="adc_power",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="adc_rms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="fem_current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="fem_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="pam_atten",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="pam_current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="pam_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="pam_power",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="antennastatus",
            name="pam_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
