# Generated by Django 3.0.3 on 2020-08-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antennas", "0009_hookupnotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="antenna",
            name="ant_name",
            field=models.CharField(default="N/A", max_length=5),
            preserve_default=False,
        ),
    ]
