# Generated by Django 3.0.3 on 2020-08-17 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antennas", "0010_antenna_ant_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissioningIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("julian_date", models.IntegerField()),
                ("exists", models.BooleanField()),
                (
                    "related_issues",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("new_issues", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="commissioningissue",
            constraint=models.UniqueConstraint(
                fields=("julian_date",), name="julian date"
            ),
        ),
    ]
