# Generated by Django 3.0.3 on 2020-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("antennas", "0012_auto_20200818_1851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissioningissue",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
