version: '3'
services:
    redishost:
      build:
        context: .
        dockerfile: ./dockerfiles/redis_cm_docker
      user: 999:999
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      networks:
          nginx_net:
            ipv4_address: "172.21.0.3"
      volumes:
        - "/storage/dashboard_data/redis_cm:/data"
      healthcheck:
        test: redis-cli ping
        interval: 1m30s
        timeout: 10s
        retries: 3
      restart: always
    redis_celery:
      build:
        context: .
        dockerfile: ./dockerfiles/redis_celery_docker
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      volumes:
        - "/storage/dashboard_data/celery:/data/"
      networks:
          nginx_net:
            ipv4_address: "172.21.0.4"
      healthcheck:
        test: redis-cli ping
        interval: 1m30s
        timeout: 10s
        retries: 3
      restart: always
    django_db:
      image: "postgres"
      command:
        - "postgres"
        - "-c"
        - "max_connections=1000"
        - "-c"
        - "shared_buffers=30GB"
      user: 999:999
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      volumes:
        - /storage/dashboard_data/psql:/var/lib/postgresql/data
      ports:
        - 5432:5432
      env_file:
        - .env
      networks:
        nginx_net:
            ipv4_address: "172.21.0.6"
      healthcheck:
        test: pg_isready
        interval: 1m30s
        timeout: 10s
        retries: 3
      restart: always
    app:
      build:
        context: .
        dockerfile: ./dockerfiles/docker_app
      image: heranow_app:latest
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      volumes:
        - /storage/dashboard_data/media:/app/media
      env_file:
         - .env
      command: /app/dockerfiles/entrypoints/entrypoint.sh
      networks:
        nginx_net:
            ipv4_address: "172.21.0.2"
      depends_on:
        - redishost
        - redis_celery
        - django_db
      restart: always
    celery:
      image: heranow_app:latest
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      command: /app/dockerfiles/entrypoints/entrypoint_celery.sh
      env_file:
         - .env
      volumes:
        - /storage/dashboard_data/media:/app/media
      depends_on:
        - redis_celery
        - redishost
        - django_db
      restart: always
      networks:
        nginx_net:
            ipv4_address: "172.21.0.5"
    celery-beat:
      image: heranow_app:latest
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      command: /app/dockerfiles/entrypoints/entrypoint_beat.sh
      env_file:
         - .env
      depends_on:
        - redis_celery
        - redishost
        - django_db
      restart: always
      networks:
        nginx_net:
            ipv4_address: "172.21.0.7"
    nginx:
      image: nginx:1.13
      logging:
        driver: "json-file"
        options:
            max-size: "100m"
      env_file:
         - .env
      ports:
        - $PORT:443
      volumes:
        - ./dockerfiles/nginx:/etc/nginx/conf.d
        - /home/locoadmin/webhost/:/webhost
        - /storage/dashboard_data/media/:/app/media/
        - /storage/dashboard_data/crontabs/:/app/crontabs/
        - /storage/dashboard_data/notebooks/:/app/notebooks/
        - /storage/dashboard_data/nightly_movies:/app/nightly_movies/
      depends_on:
        - app
      restart: always
      networks:
        nginx_net:
            ipv4_address: "172.21.0.8"
networks:
  nginx_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/24"
