name: heranow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - astropy
  - cartopy
  - django
  - gunicorn
  - healpy
  - matplotlib
  - numpy
  - pandas
  - plotly
  - pre-commit
  - psycopg2
  - psutil
  - python-dateutil
  - pyuvdata
  - pyyaml
  - redis-py
  - setuptools-scm
  - sqlalchemy
  - tabulate
  - uvicorn
  - pip
  - pip:
    - celery>=5.0
    - dash==1.16.1
    - dash-bootstrap-components==0.10.6
    - dash-core-components==1.12.1
    - dash-daq==0.5.0
    - dash-html-components==1.1.1
    - dash-renderer==1.8.1
    - dash-table==4.10.1
    - dpd-components
    - dpd-static-support
    - django-analytical
    - django-bootstrap4
    - django-extensions
    - django-environ
    - django-plotly-dash==1.4.2
    - django-tabination
    - django-tables2
    - github3.py
    - lttb
    - Werkzeug==2.0.0
    - whitenoise
    - git+https://github.com/HERA-Team/hera_mc.git
    - git+https://github.com/HERA-Team/hera_corr_cm.git@snap2bytes
