name: heranow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - astropy
  - cartopy
  - django
  - gunicorn
  - healpy
  - matplotlib
  - numpy=1.23.1
  - pandas=1.4.3
  - plotly
  - pre-commit
  - psycopg2
  - psutil
  - python-dateutil
  - pyuvdata
  - pyyaml
  - redis-py
  - setuptools-scm
  - sqlalchemy
  - tabulate
  - uvicorn
  - pip
  - django-analytical
  - django-bootstrap4
  - django-extensions
  - django-environ
  - django-tables2
  - celery>=5.0
  - dash==1.16.1
  - dash-bootstrap-components==0.10.6
  - dash-core-components==1.12.1
  - dash-daq==0.5.0
  - dash-html-components==1.1.1
  - dash-renderer==1.8.1
  - dash-table==4.10.1
  - github3.py
  - Werkzeug==2.0.0
  - whitenoise
  - pip:
    - lttb
    - django-plotly-dash==1.4.2
    - django-tabination
    - django-cleanup
    - dpd-components
    - dpd-static-support
    - git+https://github.com/HERA-Team/hera_mc.git
    - git+https://github.com/HERA-Team/hera_corr_cm.git
