name: heranow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - astropy
  - cartopy
  - django
  - gunicorn
  - numpy
  - pandas
  - plotly
  - pre-commit
  - psycopg2
  - psutil
  - python-dateutil
  - pyuvdata
  - pyyaml
  - redis-py
  - setuptools-scm
  - sqlalchemy
  - tabulate
  - uvicorn
  - pip
  - pip:
    - celery
    - dash
    - dash-bootstrap-components
    - dash-core-components
    - dash-daq
    - dash-html-components
    - dash-renderer
    - dash-table
    - dpd-components
    - dpd-static-support
    - django-analytical
    - django-bootstrap4
    - django-extensions
    - django-plotly-dash
    - django-tabination
    - django-tables2
    - github3.py
    - lttb
    - whitenoise
    - git+https://github.com/HERA-Team/hera_mc.git
