# Generated by Django 3.0.3 on 2020-08-05 21:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_auto_20200805_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antenna",
            name="antpos_enu",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=list, size=3
            ),
        ),
    ]
