# Generated by Django 3.0.3 on 2020-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_auto_20200807_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="antenna",
            name="constructed",
            field=models.BooleanField(default=False),
        ),
    ]
