# Generated by Django 3.0.3 on 2020-08-10 22:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_antenna_constructed"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapSpectra",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("hostname", models.CharField(max_length=200)),
                ("input_number", models.IntegerField()),
                (
                    "spectra",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "eq_coeffs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=None
                    ),
                ),
                (
                    "adc_hist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.FloatField(), size=None
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Status Time")),
                ("hostname", models.CharField(max_length=200)),
                ("node", models.IntegerField(blank=True, null=True)),
                ("snap_loc_num", models.IntegerField(blank=True, null=True)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("psu_alert", models.BooleanField(blank=True, null=True)),
                ("pps_count", models.BigIntegerField(blank=True, null=True)),
                ("fpga_temp", models.FloatField(blank=True, null=True)),
                ("uptime_cycles", models.BigIntegerField(blank=True, null=True)),
                ("last_programmed_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="snapstatus",
            constraint=models.UniqueConstraint(
                fields=("hostname",), name="unique hostname"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapspectra",
            constraint=models.UniqueConstraint(
                fields=("hostname", "input_number"), name="unique snap input"
            ),
        ),
    ]
