# Generated by Django 3.0.3 on 2020-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_auto_20200810_2211"),
    ]

    operations = [
        migrations.CreateModel(
            name="HookupNotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("ant_number", models.IntegerField()),
                ("part", models.CharField(max_length=200)),
                ("note", models.TextField()),
            ],
        ),
    ]
