# Generated by Django 3.0.3 on 2020-08-26 21:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_auto_20200818_2001"),
    ]

    operations = [
        migrations.AddField(
            model_name="autospectra",
            name="eq_coeffs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(default=1), default=list, size=None
            ),
        ),
    ]
