# Generated by Django 3.0.3 on 2020-08-26 21:57

import dashboard.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_autospectra_eq_coeffs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autospectra",
            name="eq_coeffs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=dashboard.models._get_eq_default,
                size=None,
            ),
        ),
    ]
