# Generated by Django 3.0.3 on 2020-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0015_auto_20200826_2157"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="autospectra",
            constraint=models.UniqueConstraint(
                fields=("antenna", "time"), name="One antpol per time"
            ),
        ),
    ]
