# Generated by Django 3.0.3 on 2020-08-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_auto_20200826_2242"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="autospectra", name="One antpol per time",
        ),
        migrations.RemoveConstraint(
            model_name="snapspectra", name="unique snap input",
        ),
        migrations.RemoveConstraint(model_name="snapstatus", name="unique hostname",),
        migrations.AddConstraint(
            model_name="antennastatus",
            constraint=models.UniqueConstraint(
                fields=("antenna", "time"), name="One antpol status per time"
            ),
        ),
        migrations.AddConstraint(
            model_name="aprioristatus",
            constraint=models.UniqueConstraint(
                fields=("antenna", "time"), name="One antpol apriori per time"
            ),
        ),
        migrations.AddConstraint(
            model_name="autospectra",
            constraint=models.UniqueConstraint(
                fields=("antenna", "time"), name="One antpol auto per time"
            ),
        ),
        migrations.AddConstraint(
            model_name="snapspectra",
            constraint=models.UniqueConstraint(
                fields=("time", "hostname", "input_number"),
                name="unique snap input per time",
            ),
        ),
        migrations.AddConstraint(
            model_name="snapstatus",
            constraint=models.UniqueConstraint(
                fields=("hostname", "time"), name="one snap status per time"
            ),
        ),
    ]
