# Generated by Django 3.0.3 on 2020-08-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_auto_20200826_2321"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hookupnotes",
            constraint=models.UniqueConstraint(
                fields=("time", "ant_number", "part"), name="unique part note per time"
            ),
        ),
    ]
