# Generated by Django 3.0.3 on 2020-08-31 16:33

import dashboard.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_auto_20200826_2328"),
    ]

    operations = [
        migrations.AddField(
            model_name="autospectra",
            name="frequencies_downsampled",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=dashboard.models._get_dummy_default,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="autospectra",
            name="spectra_downsampled",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=dashboard.models._get_dummy_default,
                size=None,
            ),
        ),
    ]
