# Generated by Django 3.0.3 on 2020-09-02 19:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0021_auto_20200902_1821"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntToSnap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Snap mapping timestamp")),
                ("snap_hostname", models.CharField(max_length=200)),
                ("chan", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SnapToAnt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(verbose_name="Snap mapping timestamp")),
                ("snap_hostname", models.CharField(max_length=200)),
                (
                    "ants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=6), size=None
                    ),
                ),
                (
                    "inds",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="snaptoant",
            constraint=models.UniqueConstraint(
                fields=("time", "snap_hostname"),
                name="One snap to ant mappering per time",
            ),
        ),
        migrations.AddField(
            model_name="anttosnap",
            name="antenna",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.Antenna"
            ),
        ),
        migrations.AddConstraint(
            model_name="anttosnap",
            constraint=models.UniqueConstraint(
                fields=("time", "antenna"), name="One ant to snap mapping per time"
            ),
        ),
    ]
