# Generated by Django 3.0.3 on 2020-09-02 19:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0022_auto_20200902_1928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snaptoant",
            name="inds",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
