# Generated by Django 3.0.3 on 2020-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_xengchannels_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="snaptoant",
            name="node",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snaptoant",
            name="snap",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
