# Generated by Django 3.0.3 on 2020-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_auto_20200903_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antennastatus",
            name="fem_switch",
            field=models.CharField(
                choices=[("ANT", "Antenna"), ("LOAD", "Load"), ("NOISE", "Noise")],
                max_length=5,
                null=True,
            ),
        ),
    ]
