# Generated by Django 3.0.3 on 2020-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0027_auto_20200910_1615"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="antenna",
            index=models.Index(
                fields=["ant_number", "polarization"],
                name="dashboard_a_ant_num_0576c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="antenna",
            index=models.Index(
                fields=["ant_name"], name="dashboard_a_ant_nam_a9684b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="antennastatus",
            index=models.Index(
                fields=["antenna", "time"], name="dashboard_a_antenna_71ebb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="antennastatus",
            index=models.Index(
                fields=["snap_hostname", "snap_channel_number"],
                name="dashboard_a_snap_ho_764181_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aprioristatus",
            index=models.Index(
                fields=["antenna", "time"], name="dashboard_a_antenna_6dbfa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autospectra",
            index=models.Index(
                fields=["antenna", "time"], name="dashboard_a_antenna_40adf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapspectra",
            index=models.Index(
                fields=["hostname", "time"], name="dashboard_s_hostnam_53fc4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapspectra",
            index=models.Index(
                fields=["hostname", "input_number"],
                name="dashboard_s_hostnam_841615_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="snapstatus",
            index=models.Index(
                fields=["hostname", "time"], name="dashboard_s_hostnam_16a685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapstatus",
            index=models.Index(
                fields=["hostname", "snap_loc_num"],
                name="dashboard_s_hostnam_b1360e_idx",
            ),
        ),
    ]
