# Generated by Django 3.0.3 on 2020-09-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0028_auto_20200910_2215"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="autospectra",
            name="dashboard_a_antenna_40adf6_idx",
        ),
    ]
