# Generated by Django 3.1.1 on 2020-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_auto_20200915_1903"),
    ]

    operations = [
        migrations.AddField(
            model_name="hookupnotes",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
